Edit user guide introduction and guide usage
AY2324S2-CS2103T-F14-2/tp pull request #140
Opened 2024-04-02 07:14 UTC by Jayne1010

2024-04-02 07:15 UTC, Jayne1010 commented on docs/UserGuide.md
> +> :warning:**Useful Tip:**<br>
not too sure if this parts for the icons will work so im just trying out.

2024-04-02 07:15 UTC, Jayne1010 commented on docs/UserGuide.md
> +# Table of Contents
I have no idea how to do table of content, will look into it later

2024-04-03 12:32 UTC, drustanyjt requested changes
I have some opinions on stylistic differences. Refer to comments.

2024-04-03 12:32 UTC, drustanyjt commented on docs/UserGuide.md
> +# Table of Contents
I thought we don't need a Table of Contents since the online version comes with a sidebar, and the pdf version comes with if we generate it correctly?

2024-04-03 12:32 UTC, drustanyjt commented on docs/UserGuide.md
> +> :warning:**Useful Tip:**<br>
actually you can test out on your own computer using npm, but I presume you mean you want to merge the PR and see what this looks like on the project website?

2024-04-03 12:32 UTC, drustanyjt commented on docs/UserGuide.md
> +Welcome to the comprehensive user guide for ClinicMate! Our goal is to provide you with the knowledge and tools necessary to make the most of ClinicMate, your essential tool for clinic management. Wh
Seems abit weird to Welcome the readers twice?

2024-04-03 13:29 UTC, Jayne1010 commented on docs/UserGuide.md
> +> :warning:**Useful Tip:**<br>
wait how do I test using npm help me

2024-04-03 13:30 UTC, Jayne1010 commented on docs/UserGuide.md
> +# Table of Contents
oh wait I want to show your my friend's UG, then you will getz

2024-04-03 16:35 UTC, drustanyjt approved these changes

2024-04-03 16:37 UTC, merged