Update edit command testv1.2b
AY2324S2-CS2103T-F14-2/tp pull request #93
Opened 2024-03-21 09:09 UTC by Jayne1010

2024-03-21 14:39 UTC, drustanyjt requested changes
Got a comment about using IC (PIN), the rest LGTM

2024-03-21 14:39 UTC, drustanyjt commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +            + "Parameters: IC (Personal Identification Number) "
change to National Registration Identity Card (NRIC) instead of PIN?

2024-03-22 07:08 UTC, drustanyjt approved these changes
LGTM

2024-03-22 07:09 UTC, merged

2024-03-24 08:13 UTC, tengcharmaine commented
closes #42 also.